export enum RaceStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
  POSTPONED = 'POSTPONED',
  CANCELLED = 'CANCELLED',
  INTERRUPTED = 'INTERRUPTED',
  SHORTENED = 'SHORTENED',
  PROVISIONAL = 'PROVISIONAL',
  RESCHEDULED = 'RESCHEDULED',
}
